### ISSUE TITLE
Release your code

### ISSUE THREAD

**Issue by JJBOY** [jonmun/MM-SADA_Domain_Adaptation_Splits#1]
Do you have any plans to open source your code？ It's a new dataset and it's not easy to reproduce your results.

**Comment by jonmun** [comment]
At the moment we do not have plans to release the code, please email jonathan.munro@bristol.ac.uk if you have some issues regarding implementation.

**Comment by jonmun** [comment]
To aid reproducibility, we are now in the process of preparing our code for release, this will be made available as soon as it is ready.

**Comment by jonmun** [comment]
The code has now been released here: https://github.com/jonmun/MM-SADA-code
